fieldLayouts:
  f8715c26-b651-42d7-917e-52fba361e636:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Link Text'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 559e1aa9-8158-4e4e-af36-3eabe0a94067
            instructions: ''
            label: 'Link URL'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: navigation
hasTitleField: true
name: Navigation
section: 46e8306b-b484-484f-ab4c-83e51c29197a
sortOrder: 1
titleFormat: '{myCustomField}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
