fieldLayouts:
  e8cb13e4-d910-43f6-aad2-9edaab292b21:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: services
hasUrls: true
name: Services
settings:
  path: '@webroot/images/'
sortOrder: 1
type: craft\volumes\Local
url: '@web/images/'
