fieldLayouts:
  91eeaed9-cf68-429c-b79a-8e537220876c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 559e1aa9-8158-4e4e-af36-3eabe0a94067
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: socialMedia
hasUrls: true
name: 'Social Media'
settings:
  path: '@webroot/images/'
sortOrder: 2
type: craft\volumes\Local
url: '@web/images/'
