contentColumnType: string(255)
fieldGroup: 90753359-f84f-4cca-b2f1-7433b4f42af1
handle: careers
instructions: ''
name: Careers
searchable: false
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
