contentColumnType: text
fieldGroup: ea6a5c42-dd3e-43b1-948a-756d6ee55796
handle: contactUsMessage
instructions: ''
name: 'Contact Us Message'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
