contentColumnType: string(255)
fieldGroup: 90753359-f84f-4cca-b2f1-7433b4f42af1
handle: facebook
instructions: ''
name: Facebook
searchable: false
settings:
  maxLength: '255'
  placeholder: 'https://facebook.com/'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
