contentColumnType: text
fieldGroup: 15af0e62-9039-4df3-96ca-fd86c57b5595
handle: serviceExcerpt
instructions: ''
name: 'Service excerpt'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 73e03827-a77e-4ab1-9e96-33a481a82dd9
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
