contentColumnType: text
fieldGroup: 15af0e62-9039-4df3-96ca-fd86c57b5595
handle: serviceTitle
instructions: ''
name: 'Service title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
