enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7846378f-4dcb-46ac-9b76-c9997e2dd3bc:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
