enableVersioning: true
handle: navigation
name: Navigation
propagationMethod: all
siteSettings:
  7846378f-4dcb-46ac-9b76-c9997e2dd3bc:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'navigation/{slug}'
structure:
  maxLevels: null
  uid: e4a9b23b-39eb-4dd7-9b36-a9c52fbb6a33
type: structure
